-- Run this SQL in your Supabase project SQL editor
-- https://supabase.com/dashboard/project/_/sql/new

-- Profiles (extends Supabase auth.users)
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  bio text default '',
  convention_history text default '',
  autofill_enabled boolean default true,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Testimonials
create table public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  author_name text not null,
  convention text not null,
  story text not null,
  impact_level text default 'Moderate',
  approved boolean default false,
  user_id uuid references auth.users(id) on delete set null
);

alter table public.testimonials enable row level security;

create policy "Anyone can read approved testimonials"
  on public.testimonials for select
  using (approved = true or auth.uid() = user_id);

create policy "Authenticated users can insert"
  on public.testimonials for insert
  with check (auth.role() = 'authenticated');

-- Comments
create table public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  author_name text not null,
  text text not null,
  user_id uuid references auth.users(id) on delete set null
);

alter table public.comments enable row level security;

create policy "Anyone can read comments"
  on public.comments for select
  using (true);

create policy "Authenticated users can insert comments"
  on public.comments for insert
  with check (auth.role() = 'authenticated');

-- Create a trigger to auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
